version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.14-management
    ports:
    - 15672:15672
    networks:
      - pipeline_net

  reader:
    container_name: reader
    image: reader:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REVIEWS_PATH=/data_reviews/yelp_academic_dataset_reviews.json
      - REVIEWS_MESSAGE_SIZE=100
      - REVIEWS_ROUTING_KEY=reviews_queue
      - BUSINESS_PATH=/data_reviews/yelp_academic_dataset_reviews.json
      - BUSINESS_MESSAGE_SIZE=100
      - BUSINESS_ROUTING_KEY=business_queue
      - EXCHANGE_REQUESTS=exchange_requests
    volumes:
    - "./reduced_data/reviews:/data_reviews"
    - "./data/business:/data_business"
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - pipeline_net

  business_controller:
    container_name: business_controller
    image: business_controller:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - BUSINESS_QUEUE=business_queue
      - BUSINESS_EXCHANGE=business_exchange
      - BUSINESS_MESSAGE_SIZE=1025
      - EXCHANGE_REQUESTS=exchange_requests
    restart: on-failure
    networks:
      - pipeline_net

  review_controller:
    container_name: review_controller
    image: review_controller:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REVIEWS_QUEUE=reviews_queue
      - WEEKDAY_QUEUE=weekday_queue
      - WEEKDAY_AGGREGATORS_QUANTITY=2
      - REVIEWS_MESSAGE_SIZE=1025
      - EXCHANGE_REQUESTS=exchange_requests
    restart: on-failure
    networks:
      - pipeline_net

  aggregator_1:
    container_name: aggregator_1
    image: aggregator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SOURCE_QUEUE=weekday_queue
      - REDUCER_QUEUE=weekday_reducer_queue
    restart: on-failure
    networks:
      - pipeline_net

  aggregator_2:
    container_name: aggregator_2
    image: aggregator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SOURCE_QUEUE=weekday_queue
      - REDUCER_QUEUE=weekday_reducer_queue
    restart: on-failure
    networks:
      - pipeline_net

  reducer:
    container_name: reducer
    image: reducer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AGGREGATED_DATA_QUEUE=weekday_reducer_queue
      - SINK_QUEUE=sink_queue
      - AGGREGATORS_QUANTITY=2
    restart: on-failure
    networks:
      - pipeline_net

  joiner:
    container_name: joiner
    image: joiner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - CRITICAL_DATA_EXCHANGE=business_exchange
    restart: on-failure
    networks:
      - pipeline_net


networks:
  pipeline_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.128.0/24