version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.14-management
    ports:
    - 15672:15672
    networks:
      - pipeline_net

  reader:
    container_name: reader
    image: reader:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REVIEWS_PATH=/data/yelp_academic_dataset_reviews.json
      - REVIEWS_MESSAGE_SIZE=100
      - REVIEWS_BY_DAY_QUEUE=by_day_queue
      - REVIEWS_BY_DAY_AGGREGATORS=2
    volumes:
    - "./reduced_data/reviews:/data"
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - pipeline_net

  aggregator_1:
    container_name: aggregator_1
    image: aggregator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SOURCE_QUEUE=by_day_queue
      - REDUCER_QUEUE=by_day_reducer_queue
    restart: on-failure
    networks:
      - pipeline_net

  aggregator_2:
    container_name: aggregator_2
    image: aggregator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SOURCE_QUEUE=by_day_queue
      - REDUCER_QUEUE=by_day_reducer_queue
    restart: on-failure
    networks:
      - pipeline_net

  reducer:
    container_name: reducer
    image: reducer:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AGGREGATED_DATA_QUEUE=by_day_reducer_queue
      - SINK_QUEUE=sink_queue
      - AGGREGATORS_QUANTITY=2
    restart: on-failure
    networks:
      - pipeline_net

  joiner:
    container_name: joiner
    image: joiner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SOURCE_QUEUE=funny_reviews_queue
      - REDUCER_QUEUE=joined_funny_reviews_reducer_queue
      - FILE_PATH_TO_JOIN=/data/yelp_academic_dataset_business.json
      - JOIN_FIELD=business_id
      - TABLE_FIELDS=[business_id, city]
    restart: on-failure
    volumes:
    - "./data/business:/data"
    networks:
      - pipeline_net


networks:
  pipeline_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.128.0/24